### ISSUE TITLE
How to handle RDF-centric specifications

### ISSUE THREAD

**Issue by Janonard** [RustAudio/rust-lv2#23]
I recently added the `units` crate to the project because the `atom` crate needs some of the URIs of that specification. It didn't need much and therefore, I kept it simple and bound the important URIs to marker types.

However, reading through the specification raised the question: How do you properly handle specifications that only introduce RDF structures? [Units](http://lv2plug.in/ns/extensions/units/units.html) isn't the only RDF-centric spec; There is also [Buf Size](http://lv2plug.in/ns/ext/buf-size/buf-size.html), [Morph](http://lv2plug.in/ns/ext/morph/morph.html), [Options](http://lv2plug.in/doc/html/group__options.html), [Parameters](http://lv2plug.in/ns/ext/parameters/parameters.html), [Patch](http://lv2plug.in/ns/ext/patch/patch.html), [Port Groups](http://lv2plug.in/ns/ext/port-groups/port-groups.html), [Port Properties](http://lv2plug.in/ns/ext/port-props/port-props.html), [Presets](http://lv2plug.in/ns/ext/presets/presets.html) and [Time](http://lv2plug.in/ns/ext/time/time.html). All of these specifications have to be handled in one way or another, but how?

To a plugin's code, these specifications aren't that important: They are only used in the configuration files of the plugin and therefore don't appear that much in the code. In special cases, such as `units`, it's sufficient to simply bind the URIs to some types and you're done. However, a host needs to know the structure and the relationship of these URIs to parse and understand the configuration files. Therefore, the handling of those specifications needs to contain more information than just the URIs.

From my point of view, we need a RDF representation crate that is capable of working with `UriBound`s. `UriBound` is quite a nice ecosystem and it would be great if it would also be used for RDF structures. An implementation the [Dynamic Manifest specification](http://lv2plug.in/ns/ext/dynmanifest/dynmanifest.html) would need a way to define RDF structures in Rust too. However, there are already a lot of RDF libraries out there; A custom one would be only one among many. One option would be to modify one: We could try to find one that is close enough for our needs and propose the changes needed for the inclusion of `UriBound`s. However, this may not end up like we would like it to be or the maintainer of that crate could uncooperative. Then, we would have to create our own crate anyway.

Another nice thing to have would be a procedural macro that can read a Turtle file and emits type and constant definitions equivalent to that file. This could be used to bind the contents of a RDF-centric specification to a crate at build time, which could make plugin discovery faster and less error-prone.

These are just some of my ideas, what do you think about it?

**Comment by YruamaLairba** [comment]
Hello,

I looked on crates.io crates for RDF/turtle, i found five, but only one retain my attention, it called [rio_turtle](https://crates.io/crates/rio_turtle). here is a summary of what i looked on those 5 crates:

### rio_turtle (tested)
* \+ parsing work on most lv2 ttl i tried on my system, Only 2 failures
* \+ seems lightweight
* \+ dev are active and responsive. I signaled an issue with relatives iri, the tomorrow it was fixed.
* \- impossible to treat or skip faulty node, you can just throw away the file (but this may change)
* \- doesn't have relationship tool.


### rdf (broken)
* \- parsing return error on many lv2 ttl on my system :(.
* \- seems it's a work in progress that don't progress anymore.
* \+ can build a graph
* \- the parsing can only build graph, no possibility to get directly the "triple" .

### Sophia (not tested)
it use rio_turtle to parse files
* \+ seems to provide relationship tool (graph)
* \- seems to have many dependencies
* \- license CeCILL B and C, may be incompatible with apache or mit ( CeCILL C seems close to LGPL)

### serd-sys (not tested)
it's a binding to the famous drobilla serd library
* \- This would make the building process more difficult
* \- No documentation at all, look like unfinished work

### chelone (not tested)
* \- very poorly documented, seems unfinished, and probably dead because the repo is archived.

**Comment by Janonard** [comment]
That's very insightful, thanks for the research! However, this issue is more about the question: How do we ship the triples (the semantics) of the Turtle files to the framework users?

I haven't spend much thought on this topic and definitely haven't made up my mind yet, but it's an open and interesting question nonetheless. How would you approach the problem?

**Comment by YruamaLairba** [comment]
Sorry, i don't have yet a clear idea of what to do in the framework with RDF turtle. Before doing those research, i didn't even know that RDF is a different thing from turtle. Initially, i looked here to see if i can generate some Rust code with it, but it's unclear what to generate. So It was more a background research.

**Comment by YruamaLairba** [comment]
I modified my first comment because i evaluated the serialization of some libs. Seems we haven't yet a decent rust turtle library able to parse, serialize and manipulate a RDF turtle graph :frowning_face:

**Comment by Janonard** [comment]
I've moved the discussion to the [Rust Audio discourse](https://rust-audio.discourse.group/t/rdf-handling-for-rust-lv2/233) since it's a very general, ecosystem design discussion.
