### ISSUE TITLE
Solve multithreading safety issue.

### ISSUE THREAD

**Issue by YruamaLairba** [RustAudio/rust-lv2#52]
As i mentioned [here](https://github.com/RustAudio/rust-lv2/issues/35#issuecomment-593676054), my current implementation of the worker spec introduce an unsafty because it allow concurrent access to the plugin in an uncontrolled way. Unfortunately, this safety issue is a global consideration and can't be solved fully in the worker crate, that's why i opened a new issue.

**My suggestion:**
* In a first time, i can publish a worker version where the `work` thread can't access to the plugin. This just suppress the problem origin, and this limits what can be done in the `work` thread, but this is easy to do and this avoid plugin designers to clutter their code with mutex when they don't have concurrency.
* In a second time, we can implement a variant of the plugin trait with threadsafe interface. This may a lot of work because it may involve many code duplication, but this allow plugin designers to do more advanced task in the `work` thread.

**What i tried/thought:**
* To have a variant of the plugin trait, i tried to explore the use of "cargo features" to adapt plugin trait method depending the need. I discovered it's a bad idea, features aren't supposed to be used in this way. When a feature is enabled, it's enabled for the whole project, or worst, for a whole workspace. As consequence, it's impossible to mix variant in a bundle.
* I quickly looked on the macro_rules side, but i don't see how to use it without making things more difficult.

**Other idea(s) for plugin traits variant:**
My current idea is to create a `PluginBase` gathering all common things between the variant, and use it as supertrait for the 2 plugin variant. Same for PluginInstance.

Does someone have a better idea for plugin variant?
When we do that ? after integrating a first version of the worker in the develop branch ? before ? After having improved some other aspect (like features) ?

**Comment by Janonard** [comment]
What exactly is the problem? Would you please describe exactly what situation you're thinking of and why it is bad?

As far as I understood it, you're saying that the `run` and the `work` method may concurrently modify the plugin. Of course, this is something that may never happen, but as far as I understand it, it will not happen:

The [specification of the `work` method](https://lv2plug.in/doc/html/group__worker.html#a22e23b44466088919fc1569dd92e2cae) says that we may not make any assumptions about which thread calls this method and that only one call may be executed at a time. This means that we are allowed to assume that there is only one mutable reference to the plugin! However, this also means that the plugin must be `Send`, but plugins are already `Send` due to the trait's supertraits. Therefore, I don't see any threading issues here.

Did I get you right or are you thinking of something else?

**Comment by YruamaLairba** [comment]
> The specification of the work method says that we may not make any assumptions about which thread calls this method...
That's just refers to the fact that threading details are managed by the host and can't be known or guessed from the plugin side.
> ...and that only one call may be executed at a time.
That's just means you can't have several threads calling `work` method at same time, that's doesn't mean you can't have a thread calling `run` and another calling `work` at same time.

**Comment by Janonard** [comment]
Okay, you're right with that: This basically means that the `work` method should receive an immutable reference instead of a mutable one. But apart from that, where's the problem?

In most cases, we have to provide mutable references, either because the [core threading rules](https://lv2plug.in/ns/lv2core/lv2core.html) allow it or since mutex lock allocation is not a real-time-safe task.

**Comment by YruamaLairba** [comment]
>This basically means that the work method should receive an immutable reference instead of a mutable one.

That not enough to ensure thread safety. if you have a `run(&mut self)` and a `work(&self)`, the work method can read a big structure while run modify it. In this case, data read in the work method can be incoherent. In safe rust, this is normally avoided by the borrowing rules: you can't have a mutable and an immutable borrow at same time.

>In most cases, we have to provide mutable references, either because the core threading rules allow it...

Yes, the core threading rules **alone** doesn't permit concurrent access to the same plugin instance, so in this case, it's safe to provide mutable references everywhere. 
However, in some ways, the worker extension introduce new threading rules that permit concurrent access to the same plugin instance, in this case, we should respect the rust borrowing rules to make it safe. This can be achieved in 2 situations:
* no plugin access in `work` method and mutable references elsewhere.
* non-mutable reference everywhere.

>...since mutex lock allocation is not a real-time-safe task

Two things here:
* real-time-safety is only required for hardRTCapable. Even if this rules should be followed, there is many case where it's impossible to do. For example, FFT algorithm break the 4th rule.
* mutex have a `try_lock` method that doesn't block the thread, i think it's compliant with hardRTCapable.

Sorry to be long, but i want you understand the issue and how it can be solved.

**Comment by Janonard** [comment]
> Sorry to be long, but i want you understand the issue and how it can be solved.

Don't worry, this is exactly the answer I asked for! :wink: 

> That not enough to ensure thread safety. if you have a `run(&mut self)` and a `work(&self)`, the work method can read a big structure while run modify it. In this case, data read in the work method can be incoherent. In safe rust, this is normally avoided by the borrowing rules: you can't have a mutable and an immutable borrow at same time.

Yes, that's absolutely true; You've convinced me. However, making `self` immutable for `run` too and using mutexes instead isn't an option to me, since it adds extra overhead to the plugin. Also, what do we do if we can not retrieve a handle for `run`? Simply not running it may lead to plugin bugs that are hard to discover, and leaving it up to the creators to handle mutexes adds additional boilerplate code for plugins that don't need it.

From my point of view, making `work` static/not giving it access to the plugin is the only proper solution. You can move any parameters to `work` you like, do the work based on the input, and pass the results back to `work_response`, which is in the "Audio" threading class and therefore able to apply them to a plugin instance.

As far as I understand it, this would solve the whole problem, wouldn't it?

**Comment by YruamaLairba** [comment]
i'm not sure you correctly understand my "immutable reference everywhere" solution:
* It's for some advanced task that are difficult, maybe impossible or just less efficient otherwise. For example, some peoples use their own buffer between `run` and `work` because the amount of data that you can pass through `schedule_work` is limited and unknown.
* To implement if from rust-lv2 side, we just need to provide traits with methods using `&self` instead of `&mut self`. No Mutex here! Seems we also need  to take a special care about explications and examples :-)
* Mutex (or RwLock or somehting else) usage is a plugin implementor responsibility, so it their problem to use correctly.

This solution is probably difficult to understand with just explanation. Personnaly, i did some piece of code simulating a host and a plugin to highlight the issue and to know how to solve it. I needed to read again the "fearless concurrency" part of the rust learning book before having a solution, and the first solution i found was this one. The idea of removing plugin reference from work method only came after.

I think i should show you this piece code after i cleaned it and gave some explanation in comment.

**Comment by YruamaLairba** [comment]
@Janonard i cleaned my "host_plugin" simulator, it's [here](https://github.com/YruamaLairba/Draft/tree/master/rust/lv2_host_workerplug). If you look the plugin methods, they all take an immutable reference to the plugin. This methods also represent the interface provided by rust-lv2 through traits. I also show how a plugin implementor can use Mutex to give mutable access to the plugin field. With the way i use Mutex here, i always get immediately the lock. If it's not the case, i choose to panic because that mean i did something wrong.

And for peoples wanting to do some aggressive optimizations, they can use [this unsafe trick](https://doc.rust-lang.org/std/cell/struct.UnsafeCell.html#examples) to bend the rules and make a fake mutex that does nothing except giving mutable reference to the inner value.

**Comment by Janonard** [comment]
As far as I know, there are four possibilities to solve this problem:
1) Give both `run` and `work` a `&mut self`.
2) Give `run` a `&mut self` and `work` a `&self`.
3) Give both `run` and `work` a `&self` and use mutexes to handle mutation.
4) Give `run` a `&mut self` and `work` no access at all.

Obviously, the first one isn't allowed since `run` and `work` may be called concurrently from different threads. Due to this reason, the second option isn't allowed either.

The third approach does not violate the borrowing rules and in theory gives both the `run` method and the `work` method mutable access to the plugin, if they need it. However, this approach may lead to several bad scenarios:

[The specifications](https://lv2plug.in/doc/html/group__worker.html#a48648b995e558a6cafeae29684c2ad93) allow the host to call `work` directly in `work_schedule`. Let's assume that the plugin contains a Mutex called `mutex` and that both `run` and `work` need to have access to `mutex` in order to execute their actions. If `run` locks the mutex and calls `schedule_work`, the `work` method may be executed instantly. Since `run` has already locked `mutex` and will not free it until `work` is done, the program will freeze when `work` tries to lock `mutex`; It's a deadlock. An example to show what I mean:
``` Rust
use std::sync::Mutex;

fn work(data: &Mutex<f32>) {
    *data.lock().unwrap() = 17.0;
}

fn run(data: &Mutex<f32>) {
    let mut ac = data.lock().unwrap();
    work(data); // Called by `schedule_work`.
    *ac = 42.0;
}

fn main() {
    let data: Mutex<f32> = Mutex::new(0.0);
    run(&data);
    println!("Value: {}", data.into_inner().unwrap());
}
```

Another scenario the spec allows: The `work` method is running in it's own thread and has locked `mutex`. Then, the host calls `run`, which also tries to lock `mutex`. Since `mutex` is already locked, the `run` method has no other choice than to panic, which might lead to the whole application crashing.

You see: The only scenario where the third approach works is when only either an instance of `run` or an instance of `work` is running, not both at the same time. This is the same reason why the first two options aren't allowed too.

This means that only option four is left over: Giving `run` full access to the plugin and `work` none at all.

I've got another problem with your approach: It adds new boilerplate code for plugins that don't need the worker specification. Assume a plugin that doesn't use worker specification, but needs to manipulate it's state in every `run` call. Then, it needs to lock a mutex and add a `panic` case, although doesn't need to. We're advertising with the fact that we require less boilerplate code than the C API and simple plugins already contain more boilerplate code than I would like to, so please do not add more.

**Comment by YruamaLairba** [comment]
> You see: The only scenario where the third approach works is when only either an instance of run or an instance of work is running, not both at the same time. This is the same reason why the first two options aren't allowed too.

For me, you miss an important details here. 1th and 2th options **break the rust safety rules** whereas the 3th **doesn't**. In other word, having deadlock is compliant with rust safety rules, so for me it's not an issue to let happen even if it's bad. So it's to plugin implementor to ensure no deadlock with rust-lv2 , in the same way it's to a rustacean to ensure no deadlock with his rust code.

>I've got another problem with your approach: It adds new boilerplate code for plugins that don't need the worker specification.

I totally agree. I never wanted to choose between the 3th and the 4th approach. Instead, i want to allow plugin implementors to choose between this 2 approach and i think it's possible. The major difficulty i think,  is to gather identical part of this 2 approach to avoid too much code replication. But I prefer to finalize the "no plugin access  from worker" approach before.
